"""One-shot helper: render 24x24 1bpp rate-source icons as C arrays.

Run this manually whenever the icon designs need to change, then paste the
output into meteorite_layout.c. Not built by the firmware itself; kept here
so the source-of-truth pixel patterns live next to the rendered bytes.

CLAUDE is hand-drawn ASCII art. The Codex pattern is generated by a rose
curve (r = inner + amp*|cos(3*theta)|) — 6 lobes that read as a hexagonal
flower/knot, evoking the ChatGPT brand mark at 24x24 1bpp.

Patterns are 24x24 grids of '#' (pixel on) / '.' (pixel off).
"""

import math

# Anthropic Sona — 8-ray asterisk. Reference: claude.ai favicon / Anthropic
# brand mark. Rendered as orthogonal cross + diagonal X, thick strokes.
CLAUDE = [
    "...........###..........",
    "...........###..........",
    "...........###..........",
    "...........###..........",
    "..#........###........#.",
    "...##......###......##..",
    "....##.....###.....##...",
    ".....##....###....##....",
    "......##...###...##.....",
    ".......##..###..##......",
    "........##.###.##.......",
    "########################",
    "########################",
    "........##.###.##.......",
    ".......##..###..##......",
    "......##...###...##.....",
    ".....##....###....##....",
    "....##.....###.....##...",
    "...##......###......##..",
    "..#........###........#.",
    "...........###..........",
    "...........###..........",
    "...........###..........",
    "...........###..........",
]

# OpenAI / ChatGPT mark — 6-lobe rose curve. The actual ChatGPT logo is a
# hexagonal knot of 6 interlocking lobes; at 24x24 1bpp the cleanest
# evocation is a polar rose r = inner + amp*|cos(3*theta)|, which yields
# 6 rounded petals around a central void. Thicker outline + tiny inner
# notch gives it a "knot" feel without trying to faithfully render the
# interweaving (impossible at this resolution).
def render_codex_rose():
    inner_r = 4.5
    amp = 6.5
    rows = []
    for y in range(24):
        row = []
        for x in range(24):
            dx = x - 11.5
            dy = y - 11.5
            r = math.hypot(dx, dy)
            theta = math.atan2(dy, dx)
            # Rotate by 90 deg so a petal points up (matches typical
            # ChatGPT logo orientation).
            target_r = inner_r + amp * abs(math.cos(3 * theta + math.pi / 2))
            # Thick outline around the curve; small inner void at the center.
            outline_in  = target_r - 2.8
            outline_out = target_r + 0.6
            on = (outline_in <= r <= outline_out) and (r >= 1.8)
            row.append("#" if on else ".")
        rows.append("".join(row))
    return rows

CODEX = render_codex_rose()


def render(name: str, rows):
    assert len(rows) == 24, f"{name}: need 24 rows, got {len(rows)}"
    bytes_out = []
    for y, row in enumerate(rows):
        assert len(row) == 24, f"{name} row {y}: need 24 cols, got {len(row)}"
        for byte_idx in range(3):
            b = 0
            for bit in range(8):
                col = byte_idx * 8 + bit
                if row[col] == "#":
                    b |= 1 << (7 - bit)
            bytes_out.append(b)
    return bytes_out


def emit_c(name: str, rows):
    data = render(name, rows)
    print(f"static const uint8_t rate_icon_{name}_map[] = {{")
    for y, row in enumerate(rows):
        triplet = data[y * 3:(y + 1) * 3]
        hex_str = ", ".join(f"0x{b:02X}" for b in triplet)
        # show the visual pattern in a trailing comment for review
        visual = row.replace(".", " ")
        print(f"    {hex_str},  /* {visual} */")
    print("};")
    print()


if __name__ == "__main__":
    emit_c("claude", CLAUDE)
    emit_c("codex", CODEX)
